# Site configuration

title = "Danish Bin Sofwan"
baseURL = "/"
copyright = "Copyright &copy; {year} Danish Bin Sofwan"
googleAnalytics = ""

theme = "academia-hugo"
enableGitInfo = false
defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false
removePathAccents = true
pagination.pagerSize = 10
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[services]
  [services.disqus]
    Shortname = ""

[build]
  noJSConfigInAssets = false
  useResourceCacheWhen = 'fallback'
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/.*\\.(js|ts|jsx|tsx)'
    target = '(js|scripts|javascript)'
  [[build.cachebusters]]
    source = 'assets/.*\\.(css|sass|scss)$'
    target = '(css|styles|scss|sass)'
  [[build.cachebusters]]
    source = 'assets/.*\\.(.*)$'
    target = '$1'

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[blackfriday]
  hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[markup.goldmark.renderer]
  unsafe = true

[caches]
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
